name: Build Linux Kernel

on:
  push:
    paths:
      - 'linux'

jobs:
    build:
      runs-on: ubuntu-20.04

      steps:
      - uses: actions/checkout@v2

      - name: Download Linux
        run: wget https://github.com/joeyl123/linux/archive/$(git rev-parse HEAD:linux).zip -0 linux.zip
      - name: Unzip
        run: unzip linux.zip
      - name: Build
        run: ./build-linux.sh linux-$(git rev-parse HEAD:linux) tinyconfig

