
name: test make

on:
  push:
    paths:
      - 'test/**'
      
jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: test make
        run: make -C test
